language: java
jdk:
  - openjdk8
sudo: required
services:
  - docker

before_script:
  - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.17.0/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/

install:
  - bash scripts/install.sh $TRAVIS_BRANCH

script:
  - mvn clean install -DskipTests
  - docker build -t inseefr/eno-ws .

after_script:
  - bash scripts/gitbook.sh