name: Build Eno WS
# Temporary workflow to build Eno-WS in the project (to be upgraded as a "create-snapshot" workflow later)

on:
  pull_request:
    types:
      - labeled

env:
  ENO_BRANCH: 'v2-main'

jobs:

  build:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'ci-build') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Checkout Eno repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: ${{ env.ENO_BRANCH }}
          repository: InseeFr/Eno
          path: Eno

      - name: Build Eno with maven
        working-directory: ./Eno
        run: mvn clean process-classes package install --no-transfer-progress -DskipTests=true -Dmaven.javadoc.skip=true -Djar.finalName="eno-core" -B -V --file pom.xml

      - name: Build Eno-WS with maven
        run: mvn clean install --no-transfer-progress -DskipTests=true -B -V --file pom.xml

      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          name: jar
          path: target/eno-ws.jar

  remove-deploy-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: ci-build
