name: Build docker for master branch

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Checkout Eno repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: master
          repository: InseeFr/Eno
          path: Eno

      - name: Build with Maven Eno
        working-directory: ./Eno
        run: mvn clean process-classes package install -DskipTests=true -Dmaven.javadoc.skip=true -Djar.finalName="eno-core" -B -V --file pom.xml

      - name: Checkout Lunatic model repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: master
          repository: InseeFr/Lunatic-model
          path: Lunatic-model

      - name: Build with Maven Lunatic model
        working-directory: ./Lunatic-model
        run: mvn install -Djar.finalName="lunatic-model" -B -V --file pom.xml

      - name: Checkout Eno-WS repo
        uses: actions/checkout@v2

      - name: Build with Maven Eno-WS
        run: mvn clean install -DskipTests=true -B -V --file pom.xml   

      - name: Upload war
        uses: actions/upload-artifact@v2
        with:
          name: war
          path: target/*.war
  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download build
        id: download
        uses: actions/download-artifact@v2
        with:
          name: war
          path: target/*.war
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: opherogel/eno-ws:v1.3.2
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
