name: Tests

# For now the Eno library is not published in a public maven repository.
# This workflow checks out the Eno project on a specific branch.

on:
  push:
    branches:
      - 'main'
    paths:
      - 'src/**'
      - 'pom.xml'
      - '.gitignore'
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, labeled]

env:
  ENO_BRANCH: main

jobs:

  test:
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'ci-build') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Checkout Eno repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: ${{ env.ENO_BRANCH }}
          repository: InseeFr/Eno
          path: Eno

      - name: Build with Maven Eno
        working-directory: ./Eno
        run: mvn clean process-classes package install --no-transfer-progress -DskipTests=true -Dmaven.javadoc.skip=true -Djar.finalName="eno-core" -B -V --file pom.xml

      - name: Test, package and analyze with maven & SonarCloud
        run: mvn --no-transfer-progress -e verify sonar:sonar -Dsonar.projectKey=InseeFr_Eno-WS -Dsonar.organization=inseefr -Dsonar.host.url=https://sonarcloud.io
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
