name: Eno-WS XML tests

# For now the Eno library is not published in a public maven repository.
# This workflow checks out the Eno project on a specific branch.

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

env:
  JAVA_VERSION: '17'

jobs:

  eno-lib:
    if: github.event.pull_request.draft == false
    name: Check Eno lib version exists
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
    steps:
      - uses: actions/checkout@v4

      - name: Get Eno Version
        id: get-version
        run: echo "version=$(mvn help:evaluate -Dexpression=eno.version -q -DforceStdout)" >> $GITHUB_OUTPUT
      
      - name: Check Eno lib tag v${{ steps.get-version.outputs.version }} existence
        id: check-tag-exists
        uses: mukunku/tag-exists-action@v1.6.0
        with:
          repo: InseeFr/Eno
          tag: "v${{ steps.get-version.outputs.version }}"

      - name: Eno lib tag verification
        id: check-tag
        run: |
          if [[ "${{ steps.check-tag-exists.outputs.exists }}" == "false" ]]; then
            echo "The tag v${{ steps.get-version.outputs.version }} doesn't exist in Eno lib repo."
            exit 1
          fi

  test:
    needs: eno-lib
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Checkout Eno repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: "v${{ needs.eno-lib.outputs.version }}"
          repository: InseeFr/Eno
          path: Eno

      - name: Build Eno lib
        working-directory: ./Eno
        run: mvn --batch-mode clean process-classes install --no-transfer-progress -DskipTests=true -Dmaven.javadoc.skip=true

      - name: Test # and analyze with maven & SonarCloud
        run: mvn test --no-transfer-progress # -e verify sonar:sonar -Dsonar.projectKey=InseeFr_Eno-WS -Dsonar.organization=inseefr -Dsonar.host.url=https://sonarcloud.io
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
