name: Tests 

on:
  push:
    branches:
      - "**"

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Checkout Eno repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: main
          repository: InseeFr/Eno
          path: Eno

      - name: Build with Maven Eno
        working-directory: ./Eno
        run: mvn clean process-classes package install -DskipTests=true -Dmaven.javadoc.skip=true -Djar.finalName="eno-core" -B -V --file pom.xml

      - name: Checkout Lunatic model repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: master
          repository: InseeFr/Lunatic-model
          path: Lunatic-model

      - name: Build with Maven Lunatic model
        working-directory: ./Lunatic-model
        run: mvn install -Djar.finalName="lunatic-model" -B -V --file pom.xml

      - name: Test, package and analyze with maven & SonarCloud
        run: mvn -e verify sonar:sonar -Dsonar.projectKey=InseeFr_Eno-WS -Dsonar.organization=inseefr -Dsonar.host.url=https://sonarcloud.io
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
